version: '3.3'

services:

  mariadb-name:
    container_name: mariadb-name
    image: flgvn.azurecr.io/mariadb:10.6-focal
    ports:
      - 3406:3306
    restart: always
    volumes:
      - ./name-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS_ROOT
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
      TZ: Asia/Ho_Chi_Minh

  phpmyadmin-name:
    container_name: phpmyadmin-name
    image: flgvn.azurecr.io/phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1500M
      POST_MAX_SIZE: 1500M
      MAX_EXECUTION_TIME: 4000
      MAX_INPUT_VARS: 1500
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 9091:80

  php-fpm-name:
    container_name: php-fpm-name
    image: flgvn.azurecr.io/php-fpm:7.1
    restart: always
    volumes:
      - /var/www/staging/name-stg.vn.fitlg.asia:/var/www/staging/name-stg.vn.fitlg.asia
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/fpm-php.www.log
    environment:
      TZ: Asia/Ho_Chi_Minh

  nginx-name:
    container_name: nginx-name
    image: flgvn.azurecr.io/nginx:1.18.0
    ports:
      - 8081:80
    restart: always
    volumes:
      - /var/www/staging/name-stg.vn.fitlg.asia:/var/www/staging/name-stg.vn.fitlg.asia
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    environment:
      TZ: Asia/Ho_Chi_Minh
