version: '3.3'

services:

  mariadb:
    container_name: web-db
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db:/var/lib/mysql
        #- ./db:/docker-entrypoint-initdb.d
    environment: # from file .env
      MYSQL_ROOT_PASSWORD: 123456
      #MYSQL_DATABASE: $MYSQL_DB
      #MYSQL_USER: $MYSQL_USER
      #MYSQL_PASSWORD: $MYSQL_PASS
      TZ: "Asia/Ho_Chi_Minh"

  phpmyadmin:
    container_name: web-myadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      TZ: "Asia/Ho_Chi_Minh"

  php-fpm:
    container_name: web-php
    image: php:fpm
    restart: always
    volumes:
      - ./web:/var/www/html/
      - ./logs/php:/var/log/fpm-php.www.log
    environment:
      TZ: "Asia/Ho_Chi_Minh"

  nginx:
    container_name: web-nginx
    image: nginx
    ports:
      - 80:8080
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    environment:
      TZ: "Asia/Ho_Chi_Minh"
